### ISSUE TITLE
KeyError: 'event_data' - git clone "install"

### ISSUE THREAD

**Issue by zbynek-rozman** [ansible/ansible-runner-service#10]
Hi,

is this related to ansible-runner-service or ansible-runner?
Its clean installation (clone) from git, i just tweaked config.yaml to bind to specific IP:PORT.
Running on Centos7, package python36 from epel.

```
[*** ~]# pip list
Package        Version
-------------- -------
aniso8601      6.0.0  
ansible-runner 1.3.0  
asn1crypto     0.24.0 
bcrypt         3.1.6  
cffi           1.12.2 
Click          7.0    
cryptography   2.6.1  
docutils       0.14   
Flask          1.0.2  
Flask-RESTful  0.3.7  
itsdangerous   1.1.0  
Jinja2         2.10   
lockfile       0.12.2 
MarkupSafe     1.1.1  
paramiko       2.4.2  
pexpect        4.6.0  
pip            19.0.3 
psutil         5.6.1  
ptyprocess     0.6.0  
pyasn1         0.4.5  
pycparser      2.19   
PyJWT          1.7.1  
PyNaCl         1.3.0  
pyOpenSSL      19.0.0 
python-daemon  2.2.3  
pytz           2018.9 
PyYAML         5.1    
setuptools     39.2.0 
six            1.12.0 
Werkzeug       0.15.1 

[*** ~]# pip -V
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

[*** ansible-runner-service]# python3.6 ansible_runner_service.py 
Starting ansible-runner-service
Analysing local configuration options from ./config.yaml
/opt/zbynek/ansible-runner-service/runner_service/configuration.py:96: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  local_config = yaml.load(_cfg.read())
- setting target_user to root
- setting passwords to {'admin': 'admin'}
- setting token_secret to secret
- setting token_hours to 24
Analysing runtime overrides from environment variables
No configuration settings overridden
2019-03-27 13:24:43,818 - root - INFO - Loaded logging configuration from ./logging.yaml
2019-03-27 13:24:43,819 - root - INFO - Run mode is: dev
2019-03-27 13:24:43,819 - runner_service.utils - DEBUG - Checking svctoken
2019-03-27 13:24:43,821 - runner_service.utils - INFO - svctoken created
2019-03-27 13:24:43,822 - root - DEBUG - No SSH keys present in ./samples/env
2019-03-27 13:24:43,822 - root - INFO - Creating SSH keys
2019-03-27 13:24:49,216 - runner_service.utils - INFO - Created SSH public key @ './samples/env/ssh_key.pub'
2019-03-27 13:24:49,217 - runner_service.utils - INFO - Created SSH private key @ './samples/env/ssh_key'
2019-03-27 13:24:49,220 - runner_service.utils - DEBUG - Checking for the SSL keys in .
2019-03-27 13:24:49,220 - runner_service.utils - INFO - Existing SSL files not found in .
2019-03-27 13:24:49,220 - runner_service.utils - INFO - Self-signed cert will be created - expiring in 3 years
2019-03-27 13:24:49,359 - runner_service.utils - DEBUG - Writing crt file to ./ansible_runner_service.crt
2019-03-27 13:24:49,360 - runner_service.utils - DEBUG - Writing key file to ./ansible_runner_service.key
 * Serving Flask app "runner_service" (lazy loading)
 * Environment: 
 * Debug mode: on
2019-03-27 13:24:49,414 - werkzeug - INFO -  * Running on https://0.0.0.0:5001/ (Press CTRL+C to quit)
2019-03-27 13:24:59,108 - runner_service.controllers.utils - INFO - 10.10.120.105 made a request without a valid token
2019-03-27 13:24:59,111 - werkzeug - INFO - 10.10.120.105 - - [27/Mar/2019 13:24:59] "GET /api/v1/jobs/9d3f0766-5089-11e9-837c-aade9b8475b0/events HTTP/1.1" 401 -
2019-03-27 13:25:08,039 - runner_service.controllers.login - DEBUG - Request received, content-type :None
2019-03-27 13:25:08,040 - runner_service.controllers.login - INFO - 10.10.120.105 - GET /api/v1/login
2019-03-27 13:25:08,042 - werkzeug - INFO - 10.10.120.105 - - [27/Mar/2019 13:25:08] "get /api/v1/login HTTP/1.1" 200 -
2019-03-27 13:25:40,469 - runner_service.controllers.playbooks - DEBUG - Request received, content-type :application/json
2019-03-27 13:25:40,471 - runner_service.controllers.playbooks - INFO - 10.10.120.105 - POST /api/v1/playbooks/runnertest.yml, parms={'time_delay': 30}
2019-03-27 13:25:40,471 - runner_service.controllers.playbooks - INFO - Playbook run request for runnertest.yml, from 10.10.120.105, parameters: {'time_delay': 30}
2019-03-27 13:25:40,473 - runner_service.services.playbook - DEBUG - Clearing up old env directory
2019-03-27 13:25:40,480 - runner_service.services.playbook - DEBUG - Playbook 6f04223a-508b-11e9-87ab-aade9b8475b0 started in 0.0s
2019-03-27 13:25:40,481 - runner_service.controllers.playbooks - INFO - Playbook runnertest.yml, UUID=6f04223a-508b-11e9-87ab-aade9b8475b0 initiated : status=starting
2019-03-27 13:25:40,483 - werkzeug - INFO - 10.10.120.105 - - [27/Mar/2019 13:25:40] "POST /api/v1/playbooks/runnertest.yml HTTP/1.1" 202 -
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/runner.py", line 141, in run
    searchwindowsize=100)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 179, in read_nonblocking
    self._log(s, 'read')
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 130, in _log
    second_log.write(s)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/utils.py", line 254, in write
    event_data = self._emit_event(value[:match.start()], event_data)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/utils.py", line 307, in _emit_event
    self._event_callback(event_data)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/runner.py", line 65, in event_callback
    should_write = self.event_handler(event_data)
  File "/opt/zbynek/ansible-runner-service/runner_service/services/playbook.py", line 160, in cb_event_handler
    runner_cache[ident]['role'] = event_data['event_data'].get('role', '')
KeyError: 'event_data'
```

**Comment by pcuzner** [comment]
I think this is an ansible-runner 1.3 change. We're working on a new branch to change auth to mutual TLS and hit the same error there.

**Comment by jmolmo** [comment]
Confirmed. Working now to fix the problem.

**Comment by zbynek-rozman** [comment]
Yes, ansible-runner 1.2 working, thanks!

**Comment by jmolmo** [comment]
Fix is in:
https://github.com/ansible/ansible-runner-service/pull/11

**Comment by jmolmo** [comment]
https://github.com/ansible/ansible-runner-service/pull/11
is included in:
https://github.com/ansible/ansible-runner-service/pull/9
which is merged.
